feat:✨ Headerコンポーネントを実装 ( #14 )
shikosai33/shikosai33-web pull request #17
Opened 2024-10-05 05:19 UTC by yuki-waster

- close #14 
- 複数ページで使用するようなコンポーネントのためのディレクトリ`src/components`を作成。
- レスポンシブ対応これでいいのか……？状態なので特に確認お願いします。

2024-10-06 04:11 UTC, ReoHakase requested changes
以下のPRでFigma Variablesで定義されているカラーパレットと同じ色をTailwindCSSでも使えるようにしました。

TailwindCSS標準のカラーパレットは使わないので、Figmaで指定されているものと同じカラートークンを使うように修正してください！

https://github.com/shikosai33/shikosai33-web/pull/23

2024-10-10 05:52 UTC, dino3616 requested changes
だいたい LGTM 👍
アニメーションだけ消しといてくださーい
(アニメーションどういうのつけるかわかんないときはデザイナに聞いてね)

2024-10-14 00:37 UTC, ReoHakase approved these changes

2024-10-14 04:32 UTC, dino3616 approved these changes

2024-10-17 03:03 UTC, merged