feat:✨footerコンポーネントを実装した( #18 )
shikosai33/shikosai33-web pull request #19
Opened 2024-10-05 10:21 UTC by yuki-waster

- close #18 
- 相も変わらずレスポンシブ分からん上に取り合えずそれっぽい見た目にするためにflex使いすぎてるのでもう何も分からない

2024-10-06 04:12 UTC, ReoHakase requested changes
以下のPRでFigma Variablesで定義されているカラーパレットと同じ色をTailwindCSSでも使えるようにしました。

TailwindCSS標準のカラーパレットは使わないので、Figmaで指定されているものと同じカラートークンを使うように修正してください！

https://github.com/shikosai33/shikosai33-web/pull/23

2024-10-06 04:17 UTC, ReoHakase requested changes

2024-10-06 04:17 UTC, ReoHakase commented on src/components/footer.astro
> +const sponsors = [
型が厳密ではないように思えるので、以下のように変えましょう。

```ts
const SPONSERS = [
// 内容
] as const satisfies ([string, `https://${string}` | `http://${string}` | null])[]
```

これで、`([string, `https://${string}` | `http://${string}` | null])[]`を満たすことを検査しつつ、`readonly`にすることで書いてあると通りの文字列の型に狭めることができます。

あと、
- 定数は大文字ケバブケース`KEBAB_CASE`のように命名する
- URLがないなら空文字ではなく`null`で表現する
ようにした方がいいと思います。

2024-10-06 04:29 UTC, dino3616 requested changes
- #4 が解決されたので、この PR の変更対象の全ファイルをもっかい save and format してください

2024-10-06 04:29 UTC, dino3616 commented on src/components/footer.astro
> +import "../styles/global.css"
```suggestion
import "@/styles/global.css"
```

`/src` の子ディレクトリを参照するパスは全部 `@/` で記述できます
他のとこも修正しといて

2024-10-06 04:29 UTC, dino3616 commented on src/pages/index.astro
> +  <Footer></Footer>
```suggestion
  <Footer />
```

`Footer` の型は子要素を受け付けていないので、使用するときも子要素を受け付けていないことを明示するような記法を用いると後から見る人が混乱しにくいかな

2024-10-06 13:13 UTC, ReoHakase requested changes

2024-10-06 13:13 UTC, ReoHakase commented on src/components/footer.astro
> +<div
役割にあったセマンティックなHTMLを書きましょう
```html
<header>
  <nav>
    <ul>
      <li><a href="#top"><img /></a></li>
      <li><a href="#circle">サークル</a></li>
      <li><a href="#event">イベント</a></li>
      <li><a href="#staff">スタッフ</a></li>
    </ul>
  </nav>
</header>
```

2024-10-09 03:20 UTC, yuki-waster commented on src/components/footer.astro
> +<div
https://github.com/shikosai33/shikosai33-web/pull/19/commits/8fba5fcd732b37ddbcda7ded77c4d7740c6b0f69

2024-10-09 03:20 UTC, yuki-waster commented on src/components/footer.astro
> +import "../styles/global.css"
https://github.com/shikosai33/shikosai33-web/pull/19/commits/8fba5fcd732b37ddbcda7ded77c4d7740c6b0f69

2024-10-09 03:20 UTC, yuki-waster commented on src/components/footer.astro
> +const sponsors = [
https://github.com/shikosai33/shikosai33-web/pull/19/commits/8fba5fcd732b37ddbcda7ded77c4d7740c6b0f69

2024-10-09 15:17 UTC, dino3616 approved these changes

2024-10-10 14:43 UTC, ReoHakase submitted a review, later dismissed

2024-10-10 14:46 UTC, dino3616 requested changes
lint format おねしゃす

2024-10-12 10:09 UTC, ReoHakase approved these changes
LGTM

2024-10-12 10:14 UTC, dino3616 approved these changes

2024-10-12 10:14 UTC, merged