feat:✨イラストカルーセルの実装( # 29 )
shikosai33/shikosai33-web pull request #31
Opened 2024-10-06 08:14 UTC by yuki-waster

- close #29
## チケット URL

## 概要
- swiperを用いてカルーセルを実装

## レビューの丁寧さの希望

- [ ] Lv0: まったく見ないで Accept する
- [ ] Lv1: ぱっとみて違和感がないかチェックして Accept する
- [ x ] Lv2: 仕様レベルまで理解して、コードレビューする
- [ ] LV3: 仕様レベルまで理解して、コードレビュー・動作確認する

## 確認用 URL

## スクリーンショット

## その他
参考
https://zenn.dev/h_ymt/articles/cde09dc1749a2c

## チェックリスト

- [x] ビルド、テストが異常終了しないことを確認した！
- [x] 意図していないデバッグコードを全て取り除いた！
- [x] PR にレビュー重要度(high, medium, low)のラベルをつけた！

2024-10-08 17:14 UTC, ReoHakase requested changes
まずは、`bun.lockb`を更新するコミットをsquashしてforce pushしてください

2024-10-10 06:00 UTC, dino3616 requested changes

2024-10-10 06:00 UTC, dino3616 commented on src/components/slideshow.astro
> +</script>
client side で動作するコンポーネントなので `.tsx` で書いてください^〜

2024-10-12 05:23 UTC, yuki-waster commented on src/components/slideshow.astro
> +</script>
https://github.com/shikosai33/shikosai33-web/pull/31/commits/a9df59b0a4f0439b9fe7b58cebef8dd51bc6b0e2

2024-10-12 10:15 UTC, dino3616 commented on src/components/slideshow.astro
> +</script>
なんか^〜が勝手に変換されてたけど他意ないです、すまそ lgtm

2024-10-12 10:16 UTC, dino3616 commented
コンフリクト解消したら lgtm すー

2024-10-13 06:40 UTC, dino3616 approved these changes

2024-10-14 00:34 UTC, ReoHakase approved these changes

2024-10-14 04:32 UTC, merged