feat: `/event/{slug}`を実装した(#61)
shikosai33/shikosai33-web pull request #64
Opened 2024-10-19 07:17 UTC by yuki-waster

- close #61 
## チケット URL

## 概要

## レビューの丁寧さの希望

- [ ] Lv0: まったく見ないで Accept する
- [ ] Lv1: ぱっとみて違和感がないかチェックして Accept する
- [ ] Lv2: 仕様レベルまで理解して、コードレビューする
- [x] LV3: 仕様レベルまで理解して、コードレビュー・動作確認する

## 確認用 URL
`/event/{slug}`
e.g. 
- /event/gasaire-plankton
- /event/dance-club (1日目中ステージ最初)
- /event/stamp-rally (2日間開催・前後のイベント無し)

`/event`がmergeされていないので、URL手打ちで遷移してください。

## スクリーンショット
![image](https://github.com/user-attachments/assets/97248c7c-0904-46f4-9ac7-adb047cebcb7)
![image](https://github.com/user-attachments/assets/18692d3a-c2d3-4196-8039-cf6b41ec81e9)
![image](https://github.com/user-attachments/assets/958b5516-c1e1-4dbe-86ae-ad9eeedc3a2b)
![image](https://github.com/user-attachments/assets/c8921a51-ce9b-4b5e-866a-64f93e0aed79)

## その他
20行目以降の`getStaticPaths()`の実装が割とこれでいいのか？状態なので特に確認お願いします。

## チェックリスト

- [ ] ビルド、テストが異常終了しないことを確認した！
- [x] 意図していないデバッグコードを全て取り除いた！
- [x] PR にレビュー重要度(high, medium, low)のラベルをつけた！

2024-10-19 07:32 UTC, ReoHakase requested changes

2024-10-19 07:32 UTC, ReoHakase commented on src/pages/event/[slug].astro
> +        <p class="text-mauve-11 text-center font-Dela text-base">
`bg-mauve-1`でお願いします
```suggestion
        <p class="text-mauve-11 bg-mauve-1 text-center font-Dela text-base">
```

2024-10-19 07:32 UTC, ReoHakase commented on src/pages/event/[slug].astro
> +                    'inline-block text-lg text-center font-Dela text-mauve-11 text-stroke-mauve-1 text-stroke-4 paint-sfm drop-shadow-bump shadow-mauve-6',
Figmaの開発者モードの出力は`-webkit-text-stroke-width: 4;`になっているのですが、おそらく2倍の値を設定しないと同じ見た目が得られないので、`text-stroke-8`で試してみてください！
```suggestion
                    'inline-block text-lg text-center font-Dela text-mauve-11 text-stroke-mauve-1 text-stroke-8 paint-sfm drop-shadow-bump shadow-mauve-6',
```

2024-10-19 07:32 UTC, ReoHakase commented on src/pages/event/[slug].astro
> +                    'inline-block text-lg text-center font-Dela text-mauve-11 text-stroke-mauve-1 text-stroke-4 paint-sfm drop-shadow-bump shadow-mauve-6',
Figmaの開発者モードの出力は`-webkit-text-stroke-width: 4;`になっているのですが、おそらく2倍の値を設定しないと同じ見た目が得られないので、`text-stroke-8`で試してみてください！
```suggestion
                    'inline-block text-lg text-center font-Dela text-mauve-11 text-stroke-mauve-1 text-stroke-8 paint-sfm drop-shadow-bump shadow-mauve-6',
```

2024-10-19 07:32 UTC, ReoHakase commented on src/pages/event/[slug].astro
> +          class="-mt-5 pt-5 bg-[url('../assets/kawaii_text_violet.png')] bg-center bg-cover"
<img width="1772" alt="image" src="https://github.com/user-attachments/assets/ea85a625-6290-40c4-88b7-5bc1dc09dc1d">

カラーブレンドモードに焼き込みを指定し忘れています

```suggestion
          class="-mt-5 pt-5 bg-[url('../assets/kawaii_text_violet.png')] bg-center bg-cover mix-blend-color-burn"
```

2024-10-19 07:44 UTC, ReoHakase requested changes

2024-10-19 07:44 UTC, ReoHakase commented on src/pages/event/[slug].astro
> +        class="flex flex-col gap-3 p-6 rounded-3xl border border-solid border-violet-6 bg-gradient-to-b from-[#FDFCFD] to-[#FCFCFF] shadow-[0px_4px_16px_0px_rgba(51, 0, 255, 0.06)], shadow-[0px_4px_0
背景のグラデーションについては、Figmaの開発者モードからはトークン名が確認できないせいで紛らわしかったと思いますが、`mauve-1` から `violet-1` のものが使われています👀

<img width="1772" alt="image" src="https://github.com/user-attachments/assets/7abd324c-e178-41a1-993f-816d54f1639e">

`box-shadow`についても同様で、編集モードからだとトークン名が確認できます。
また、Tailwind CSSのArbitary Valueを使って影を2つつけるときは、一つのクラスにまとめないとどちらかが無視されるので、気をつけましょう。(`var(--tw-shadow)`の定義が2回宣言されて、どちらかが無視されるから)
あと、Tailwind CSSのArbitary Valueで色のトークンを使いたいときは、`src/styles/colors.css`で定義されているCSS変数を`var()`関数で参照すれば、そのまま使えます。

```suggestion
        class="flex flex-col gap-3 p-6 rounded-3xl border border-solid border-violet-6 bg-gradient-to-b from-mauve-1 to-violet-1 shadow-[0px_4px_16px_0px_var(--violet-a3),_0px_4px_0px_0px_var(--violet-9)"
```

2024-10-20 01:36 UTC, yuki-waster commented on src/pages/event/[slug].astro
> +          class="-mt-5 pt-5 bg-[url('../assets/kawaii_text_violet.png')] bg-center bg-cover"
kawaiiTextを文字として置くと縁取りの設定がよくわからなくなったので画像にしました
https://github.com/shikosai33/shikosai33-web/pull/64/commits/b8fc91431040aef68d49a75f546b38eab1b54ed6

2024-10-20 01:37 UTC, yuki-waster commented on src/pages/event/[slug].astro
> +        class="flex flex-col gap-3 p-6 rounded-3xl border border-solid border-violet-6 bg-gradient-to-b from-[#FDFCFD] to-[#FCFCFF] shadow-[0px_4px_16px_0px_rgba(51, 0, 255, 0.06)], shadow-[0px_4px_0
https://github.com/shikosai33/shikosai33-web/pull/64/commits/b8fc91431040aef68d49a75f546b38eab1b54ed6

2024-10-20 01:37 UTC, yuki-waster commented on src/pages/event/[slug].astro
> +                    'inline-block text-lg text-center font-Dela text-mauve-11 text-stroke-mauve-1 text-stroke-4 paint-sfm drop-shadow-bump shadow-mauve-6',
https://github.com/shikosai33/shikosai33-web/pull/64/commits/b8fc91431040aef68d49a75f546b38eab1b54ed6

2024-10-20 01:37 UTC, yuki-waster commented on src/pages/event/[slug].astro
> +                    'inline-block text-lg text-center font-Dela text-mauve-11 text-stroke-mauve-1 text-stroke-4 paint-sfm drop-shadow-bump shadow-mauve-6',
https://github.com/shikosai33/shikosai33-web/pull/64/commits/b8fc91431040aef68d49a75f546b38eab1b54ed6

2024-10-20 01:38 UTC, yuki-waster commented on src/pages/event/[slug].astro
> +        <p class="text-mauve-11 text-center font-Dela text-base">
ボタン(`a`タグ)全体に`bg-mauve-1`をかけました
https://github.com/shikosai33/shikosai33-web/pull/64/commits/b8fc91431040aef68d49a75f546b38eab1b54ed6

2024-10-20 04:31 UTC, ReoHakase commented on src/pages/event/[slug].astro
> +          class="-mt-5 pt-5 bg-[url('../assets/kawaii_text_violet.png')] bg-center bg-cover"
とりあえずは画像で済ませてしまいましょう

2024-10-20 04:34 UTC, ReoHakase requested changes

2024-10-20 04:34 UTC, ReoHakase commented on src/pages/event/[slug].astro
> +            class="flex flex-col justify-center items-center gap-3 p-6 rounded-3xl border border-solid border-violet-6 bg-gradient-to-b from-mauve-1 to-violet-1 shadow-[0px_4px_16px_0px_var(--violet-
影がなくなっています

<img width="1502" alt="image" src="https://github.com/user-attachments/assets/29fb6c07-6456-435d-8f2d-5b4c1239fe5a">


```suggestion
            class="flex flex-col justify-center items-center gap-3 p-6 rounded-3xl border border-solid border-violet-6 bg-gradient-to-b from-mauve-1 to-violet-1 shadow-[0px_4px_16px_0px_var(--violet-a3),_0px_4px_0px_0px_var(--violet-9)] xl:order-2"
```

2024-10-20 04:34 UTC, ReoHakase commented on src/pages/event/[slug].astro
> +        class="flex flex-col gap-3 p-6 rounded-3xl border border-solid border-violet-6 bg-gradient-to-b from-mauve-1 to-violet-1 shadow-[0px_4px_16px_0px_var(--violet-a-3),_0px_4px_0px_0px_var(--viol
影がなくなっています

<img width="1502" alt="image" src="https://github.com/user-attachments/assets/f68cb4aa-e513-4df0-9dfc-a1641fe7f4f2">


```suggestion
        class="flex flex-col gap-3 p-6 rounded-3xl border border-solid border-violet-6 bg-gradient-to-b from-mauve-1 to-violet-1 shadow-[0px_4px_16px_0px_var(--violet-a3),_0px_4px_0px_0px_var(--violet-9)]"
```

2024-10-20 10:22 UTC, yuki-waster commented on src/pages/event/[slug].astro
> +        class="flex flex-col gap-3 p-6 rounded-3xl border border-solid border-violet-6 bg-gradient-to-b from-mauve-1 to-violet-1 shadow-[0px_4px_16px_0px_var(--violet-a-3),_0px_4px_0px_0px_var(--viol
https://github.com/shikosai33/shikosai33-web/pull/64/commits/f2e378af867c67443043c369d52c42a1203165bf

2024-10-20 10:23 UTC, yuki-waster commented on src/pages/event/[slug].astro
> +            class="flex flex-col justify-center items-center gap-3 p-6 rounded-3xl border border-solid border-violet-6 bg-gradient-to-b from-mauve-1 to-violet-1 shadow-[0px_4px_16px_0px_var(--violet-
https://github.com/shikosai33/shikosai33-web/pull/64/commits/f2e378af867c67443043c369d52c42a1203165bf

2024-10-20 14:59 UTC, ReoHakase submitted a review, later dismissed
LGTM!

2024-10-20 14:59 UTC, ReoHakase commented
#75 がマージされたらビルドのエラーは無くなるので、 #75 を先にマージしてしまいましょう

2024-10-21 07:36 UTC, yuki-waster commented
ごめんなさいいろいろおかしいんで修正します

2024-10-21 12:35 UTC, ReoHakase requested changes

2024-10-21 12:35 UTC, ReoHakase commented on src/pages/event/[slug].astro
> +        class="relative flex flex-col gap-3 justify-center items-center rounded-3xl overflow-hidden bg-gradient-to-b from-violet-a-9 to-mauve-a-1"
https://05bd2316.shikosai33.pages.dev/event/high-side/

- モバイルに対しては、紫のグラデーション背景は`<Layout>`の`padding`を無視するようにする 
  - `<div>`に負のマージン`-mx-1 mt-[-88px]`を適用するとできるはず (左右の余白`4px`だけ左右に伸ばして、ヘッダー`64px`+余白`24px`分上に伸ばす)
  - 子要素の位置は変えたくないので、↑で伸びた分を打ち消すような`padding`をつける (`px-1 pt-[88px]`)

```suggestion
        class="relative flex flex-col gap-3 justify-center items-center rounded-3xl overflow-hidden bg-gradient-to-b from-violet-a-9 to-mauve-a-1 -mx-1 mt-[-88px] px-1 pt-[88px]"
```

## Figma

<img width="361" alt="image" src="https://github.com/user-attachments/assets/2cb3d0fe-3266-41c1-a352-3176c1e4c58c">

## Chrome (Sidekick)

<img width="380" alt="image" src="https://github.com/user-attachments/assets/e33b6a02-61a3-44e8-b3fb-622a686907d9">


## iOS Safari

ぼかしの要素の表示位置がiOS Safariでずれている
`inset-0`の効果は中央寄せではなく、祖先の`relative`要素の箱に対して四辺の隙間が`0`になるように引き伸ばすプロパティ。だから、ブラウザによっては中央寄せの用途で使うときは動作が異なるかも
https://developer.mozilla.org/ja/docs/Web/CSS/inset

![image](https://github.com/user-attachments/assets/b54a81bc-a2fd-4b7e-985d-a3eec6007dbf)

2024-10-21 12:35 UTC, ReoHakase commented on src/pages/event/[slug].astro
> +          <Image
ぼかし用の画像は装飾的な意味しか持たないので、スクリーンリーダーが無視するように`aria-hidden`をつける

```suggestion
          <Image aria-hidden
```

2024-10-21 12:35 UTC, ReoHakase commented on src/pages/event/[slug].astro
> +            class="w-1/2 aspect-square rounded-xl absolute justify-self-center inset-0 blur-lg opacity-50"
アー写の大きさは、Figmaでの指定の通り、モバイル`300px`, デスクトップ`450px`固定でもいいと思います
その際は、この要素にmarginをつけるか親要素にpaddingをつけて、(`32px`くらい？)`w-full`でも余白が開くようにしましょう

```suggestion
            class="w-full max-w-[300px] lg:max-w-[450px] aspect-square rounded-xl absolute justify-self-center inset-0 blur-lg opacity-50"
```

2024-10-21 12:35 UTC, ReoHakase commented on src/pages/event/[slug].astro
> +              'inline-block text-5xl font-Dela text-violet-11 text-stroke-mauve-1 text-stroke-[8px] paint-sfm drop-shadow-bump shadow-mauve-6',
- モバイルではFigmaの通りにフォントサイズを小さくしましょう
- 親の`<h2>`に`w-full`をつけて、改行されるようにしましょう

2024-10-22 01:09 UTC, yuki-waster commented on src/pages/event/[slug].astro
> +              'inline-block text-5xl font-Dela text-violet-11 text-stroke-mauve-1 text-stroke-[8px] paint-sfm drop-shadow-bump shadow-mauve-6',
https://github.com/shikosai33/shikosai33-web/pull/64/commits/c93cb13ecb47220dd76b57c03126d0df5c304d4a

2024-10-22 01:10 UTC, yuki-waster commented on src/pages/event/[slug].astro
> +            class="w-1/2 aspect-square rounded-xl absolute justify-self-center inset-0 blur-lg opacity-50"
https://github.com/shikosai33/shikosai33-web/pull/64/commits/c93cb13ecb47220dd76b57c03126d0df5c304d4a

2024-10-22 01:10 UTC, yuki-waster commented on src/pages/event/[slug].astro
> +          <Image
https://github.com/shikosai33/shikosai33-web/pull/64/commits/c93cb13ecb47220dd76b57c03126d0df5c304d4a

2024-10-22 01:10 UTC, yuki-waster commented on src/pages/event/[slug].astro
> +        class="relative flex flex-col gap-3 justify-center items-center rounded-3xl overflow-hidden bg-gradient-to-b from-violet-a-9 to-mauve-a-1"
https://github.com/shikosai33/shikosai33-web/pull/64/commits/c93cb13ecb47220dd76b57c03126d0df5c304d4a

2024-10-22 06:41 UTC, ReoHakase approved these changes

2024-10-22 07:12 UTC, merged