feat:`/event/{slug}`を実装した(#72)
shikosai33/shikosai33-web pull request #73
Opened 2024-10-20 06:48 UTC by yuki-waster

- close #72 
## チケット URL

## 概要
- サークル個別ページを実装した。
- 場所に関する情報を追加した。(commitした後に別のissueでやるべきだったと気付きました……すみません)

## レビューの丁寧さの希望

- [ ] Lv0: まったく見ないで Accept する
- [ ] Lv1: ぱっとみて違和感がないかチェックして Accept する
- [ ] Lv2: 仕様レベルまで理解して、コードレビューする
- [x] LV3: 仕様レベルまで理解して、コードレビュー・動作確認する

## 確認用 URL
https://b4d18b58.shikosai33.pages.dev/circle/1-1/ 
![image](https://github.com/user-attachments/assets/d8411578-a6b4-420b-ae09-00f188cbf46d)

## スクリーンショット
![image](https://github.com/user-attachments/assets/d6d0ba67-ae00-4c97-bc81-0289205c24e1)
![image](https://github.com/user-attachments/assets/566a9d26-42bf-4587-b1a2-b59b2eb1b39a)

## その他

## チェックリスト

- [x] ビルド、テストが異常終了しないことを確認した！
- [x] 意図していないデバッグコードを全て取り除いた！
- [x] PR にレビュー重要度(high, medium, low)のラベルをつけた！

2024-10-20 14:57 UTC, ReoHakase requested changes

2024-10-20 14:57 UTC, ReoHakase commented on src/content/circles/1-1.md
> +<p class="text-base font-Dela text-mauve-11">
`<Content />`の親要素に`text-base font-Dela text-mauve-11`を指定した方がいいと思うけど、動かなかった？Markdownにタグを書くのはできるだけ避けたいので、この実装にした理由を教えてほしいです🙏

2024-10-20 14:57 UTC, ReoHakase commented on src/pages/circle/[slug].astro
> +          <Image src={SchoolMap} alt="茨城高専構内地図" />
特に幅が広いViewportでレイアウトが崩れるので修正してほしいです

<img width="1772" alt="image" src="https://github.com/user-attachments/assets/880f5168-9cd7-4fca-93c1-bc51e6a0832f">

2024-10-21 05:16 UTC, yuki-waster commented on src/content/circles/1-1.md
> +<p class="text-base font-Dela text-mauve-11">
親要素にcss指定だとだめだな……って思ってそうしたはずなんですけど今やったら動いたので修正しました
https://github.com/shikosai33/shikosai33-web/pull/73/commits/ce0429a57ce505f85a0cdc1aefa32efaf361a1fe

2024-10-21 05:16 UTC, yuki-waster commented on src/pages/circle/[slug].astro
> +          <Image src={SchoolMap} alt="茨城高専構内地図" />
svgに余分な空白が入っていたので一部差し換えました
https://github.com/shikosai33/shikosai33-web/pull/73/commits/ce0429a57ce505f85a0cdc1aefa32efaf361a1fe

2024-10-21 05:32 UTC, ReoHakase commented on src/content/circles/1-1.md
> +<p class="text-base font-Dela text-mauve-11">
閉じる`</p>`が残ってる？

<img width="1300" alt="image" src="https://github.com/user-attachments/assets/5caed94d-178c-4263-a3ce-620e4d4d7033">

2024-10-21 05:36 UTC, ReoHakase requested changes

2024-10-21 05:36 UTC, ReoHakase commented on src/pages/circle/[slug].astro
> +  <main class="flex min-h-screen flex-col items-center justify-between p-24">
`<Layout>`側で余白をか余白を管理するように #75 で変更したので、`padding`を消してください🙏

<img width="1772" alt="image" src="https://github.com/user-attachments/assets/073fd636-c18e-4dd8-b786-9647ac53dfb9">

```suggestion
  <main class="flex min-h-screen flex-col items-center justify-between">
```

2024-10-22 07:18 UTC, ReoHakase approved these changes
とりあえず

2024-10-22 07:18 UTC, merged