43/theme intro
shikosai33/shikosai33-web pull request #76
Opened 2024-10-20 14:34 UTC by parsley001

- close #43 
## チケット URL

## 概要

rootページのテーマ紹介部分を実装した

## レビューの丁寧さの希望

- [ ] Lv0: まったく見ないで Accept する
- [x] Lv1: ぱっとみて違和感がないかチェックして Accept する
- [ ] Lv2: 仕様レベルまで理解して、コードレビューする
- [ ] LV3: 仕様レベルまで理解して、コードレビュー・動作確認する

## 確認用 URL

## スクリーンショット

変更前
![image](https://github.com/user-attachments/assets/d5c0efd4-f03d-426d-8591-c933681b8802)
変更後
![image](https://github.com/user-attachments/assets/16da1ef2-c4dd-4446-8cff-1d6718d7d6d1)

## その他

## チェックリスト

- [ ] ビルド、テストが異常終了しないことを確認した！
- [x] 意図していないデバッグコードを全て取り除いた！
- [x] PR にレビュー重要度(high, medium, low)のラベルをつけた！

2024-10-20 14:47 UTC, ReoHakase requested changes
クラス名の空白以外はLGTM!

2024-10-20 14:47 UTC, ReoHakase commented on src/components/theme.astro
> +    class="w-[100px] h-[100px] top-[65px] right-[-18px] absolute rotate-[-2.39 deg] grayscale"
空白を消すか`_`にしましょう

```suggestion
    class="w-[100px] h-[100px] top-[65px] right-[-18px] absolute rotate-[-2.39deg] grayscale"
```

2024-10-21 07:33 UTC, parsley001 commented on src/components/theme.astro
> +    class="w-[100px] h-[100px] top-[65px] right-[-18px] absolute rotate-[-2.39 deg] grayscale"
レビューありがとうございます。修正しました。

2024-10-21 19:02 UTC, ReoHakase requested changes

2024-10-21 19:02 UTC, ReoHakase commented on src/components/theme.astro
> +    src="./src/assets/heisei-heart.png"
今の画像の実装方法だと、Astroによる最適化がされず、プロジェクトルートからの相対パスでsrcを指定しているので、プロダクション環境で画像が見つかりません。

画像の読み込み方法を以下のように変えてください。
また、アクセシビリティの観点から、`alt`テキストは必ず指定してください。

- Astroの`<Image>`コンポーネントを使う https://docs.astro.build/ja/guides/images/#image--astroassets
- `widths`に、表示される大きさの1倍, 2, 3倍, 画像そのものの横幅を指定する
- `sizes`に、読み込むべき画像の横幅をビューポートの横幅ごとに指定する (今回は共通だから単に`??px`でok)
- 静的に読み込める画像は`import`文で取ってくる

## 例

```astro
---
import { Image } from 'astro:assets';
import HeiseiTiara from '@/assets/heisei-heart.png';
---

<Image src={HeiseiTiara} alt="平成っぽいティアラ" widths={[90, 180, 270, HeiseiTiara.width]} sizes="90px" class="w-[90px]" />

2024-10-21 19:02 UTC, ReoHakase commented on src/components/theme.astro
> +    <span
iOS Safariで、「ちゃぁみい！」の文字が見えなかったです

![image](https://github.com/user-attachments/assets/23f83af8-323b-4ca8-9d55-ca1c263f77ef)

2024-10-22 14:17 UTC, ReoHakase approved these changes

2024-10-22 14:17 UTC, merged