スタッフページの作成とfigma上でのFrame75を実装
shikosai33/shikosai33-web pull request #91
Opened 2024-10-21 15:00 UTC by amuratakamitamu

## チケット URL

## 概要

## レビューの丁寧さの希望
作業途中です｡
とりあえずのレビューをお願いします

- [ ] Lv0: まったく見ないで Accept する
- [ ] Lv1: ぱっとみて違和感がないかチェックして Accept する
- [ ] Lv2: 仕様レベルまで理解して、コードレビューする
- [ ] LV3: 仕様レベルまで理解して、コードレビュー・動作確認する

## 確認用 URL

## スクリーンショット
![image](https://github.com/user-attachments/assets/ca62b602-0339-453c-bb11-3dc615bb6e56)

## その他

## チェックリスト

- [ ] ビルド、テストが異常終了しないことを確認した！
- [ ] 意図していないデバッグコードを全て取り除いた！
- [ ] PR にレビュー重要度(high, medium, low)のラベルをつけた！

2024-10-22 06:56 UTC, ReoHakase requested changes

2024-10-22 06:56 UTC, ReoHakase commented on src/pages/staff.astro
> +        <img src="src/assets/LaughingGuys.png" />
素のHTMLの`<img>`はそのままクライアントに送られるので、このパスの書き方ではブラウザ側は画像の場所を解決できません。
ローカル環境では、リポジトリのルートからの相対パスとして解決されるので見えると思いますが、Cloudflareにデプロイした後はビルド結果`dist`しかホストされないので、画像は見えません。

どうしても`<img>`を使いたい場合は、画像を`public`以下に置いて、`/`から始まる絶対パスで指定してください。(リポジトリのディレクトリ構造ではなく、ホストされるパス)

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/a52561eb-cba3-4ed5-8535-8456baa96964">

https://docs.astro.build/ja/guides/images/#image--astroassets 画像を載せるときは最適化が施されない`<img>`ではなく、代わりに`astro:assets`の`<Image>`コンポーネントを使ってください。基本的に、`src`プロパティには`import`文で持ってきた画像を指定、`alt`には適切な代替テキスト *(必須)* を設定してください。できれば`widths`と`sizes`も描画される大きさに合わせて設定してほしいです。
```suggestion
        <Image src={LaughingGuys} alt="茨香祭実行委員の集合写真" />
```

2024-10-22 06:56 UTC, ReoHakase commented on src/pages/staff.astro
> +// import NotFound404Image from "@/assets/404.png";
コメントアウトはコミットに含めないようにしましょう

2024-10-22 08:21 UTC, amuratakamitamu commented
指摘いただいた点修正しましたー

2024-10-24 16:05 UTC, amuratakamitamu commented
PRをdraftからreadyに変更しました

2024-10-24 21:05 UTC, ReoHakase requested changes

2024-10-24 21:05 UTC, ReoHakase commented on src/assets/LaughingGuys.png
未使用ならこのファイルは削除してください🙏

2024-10-24 21:05 UTC, ReoHakase commented on src/pages/staff.astro
> +    <KawaiiContainer color="orange" class="relative flex flex-col items-center">
`/event/[slug]`の実装を参考に、モバイルで`padding`を無視して広がるようにしてください。

### 今の見た目

<img width="345" alt="image" src="https://github.com/user-attachments/assets/6f297abb-8b99-42f7-8107-750b782c6f78">

### `/event/[slug]`の見た目

<img width="347" alt="image" src="https://github.com/user-attachments/assets/67560299-457f-48f0-9697-7ff3330af71b">

### Figmaの見た目

https://www.figma.com/design/Ao44cG1Oi8XUiWBQM1vyk7/website?node-id=639-5447&t=SvZCfVQ92ld9FeBe-1

2024-10-24 21:05 UTC, ReoHakase commented on src/pages/staff.astro
> +          href="#HeadQuarters"
idはurlに含められるので、小文字大文字の区別がつけられないかもしれません。ケバブケース`kebab-case`に変更しましょう

```suggestion
          href="#head-quarters"
```

2024-10-24 21:05 UTC, ReoHakase commented on src/pages/staff.astro
> +        <StudentCard
コメント付きの`<StuedentCard>`はモバイルで画面幅いっぱい(2列占有?)するようにしてください。表示が崩れています。 https://tailwindcss.com/docs/grid-column

<img width="347" alt="image" src="https://github.com/user-attachments/assets/97a003a6-70ec-464d-9034-35eb2ae298f1">

```suggestion
        <StudentCard class="col-span-2"
```

2024-10-24 23:47 UTC, amuratakamitamu commented on src/assets/LaughingGuys.png
削除しました([25d121f](https://github.com/shikosai33/shikosai33-web/pull/91/commits/25d121f07d8154c1451770a44969bfb1bd883411))

2024-10-25 01:50 UTC, amuratakamitamu commented on src/pages/staff.astro
> +          href="#HeadQuarters"
修正しました([25d121f](https://github.com/shikosai33/shikosai33-web/pull/91/commits/25d121f07d8154c1451770a44969bfb1bd883411))

2024-10-25 03:01 UTC, amuratakamitamu commented on src/pages/staff.astro
> +        <StudentCard
修正しました([e62b58f](https://github.com/shikosai33/shikosai33-web/pull/91/commits/e62b58f85ad09ff9f1b31fa0ca4dab2e96c2f232))

2024-10-25 04:46 UTC, amuratakamitamu commented on src/pages/staff.astro
> +    <KawaiiContainer color="orange" class="relative flex flex-col items-center">
修正しました([2cbc862](https://github.com/shikosai33/shikosai33-web/pull/91/commits/2cbc8624463754eadf634922d7043c05784315a6))

2024-10-25 05:09 UTC, yuki-waster requested changes

2024-10-25 05:09 UTC, yuki-waster commented on src/pages/staff.astro
> +          主にこのWebサイトの作成を担当しています！メンバーが多忙な中なんとかサイトを公開できました。茨香祭当日はTwitterでステージの様子などをアップしていく予定なのでお楽しみに！
コメントを正式なものに変更してください。

---

今年のテーマ「ちゃあみぃ！」に合わせて可愛らしいホームページを制作しました。X・Instagramのフォローもよろしくお願いします！

2024-10-25 05:09 UTC, yuki-waster commented on src/pages/staff.astro
> +          茨香祭の何でも屋！運営を務めております本部です！皆さんに楽しんでもらうため部署員一同、精魂込めて活動してまいりました茨香祭を是非お楽しみください！
コメントを正式なものに変更してください

---

皆さんがサークルを出店するためのお手伝いをさせていただきました、本部の林です。とにかく楽しんで、いっぱい笑ってください。最高の思い出になるよう、大切に大切に過ごしてくださいね！

2024-10-25 05:31 UTC, yuki-waster approved these changes

2024-10-25 05:50 UTC, ReoHakase approved these changes
lgtm!

2024-10-25 05:55 UTC, merged